#!/bin/bash


function printUsage(){
	echo "To use this script specify 1 of the following flags : "
	echo " -dir DIRECTORY_PATH to run the validation on all the files inside this directory"
	echo " -file FILENAME_PATH to run validation of 1 file"
	echo " -generate will create 2 directories , 1 with positive tests called Positive"
	echo " Other one Negative will negative tests"
	echo " -help will show this message"
	echo " -h same as -help"
}

if [ $? != 0 ] ; then
 	echo "No arguments enters";
	printUsage 
	exit 1 ;
 fi
# check whether user had supplied -h or --help . If yes print usage 
if [[ ( $# == "--help") ||  $# == "-h" ]] ; then 
	printUsage
	exit 0
fi 

while [[ $# -gt 0 ]]
do
key="$1"
case $key in
	-dir|-d)
	DIRECTORY="$2"
	shift
	;;
	-file|-f)
	FILENAME="$2"
	shift
	;;
	-generate|-gen)
	GENERATE=true;
	shift
	;;
esac
shift
done


if [[ $DIRECTORY ]] ; then
	java -jar Hanoi.jar dir ${DIRECTORY}
fi
if [[ $FILENAME ]] ; then
	java -jar Hanoi.jar file ${FILENAME}
fi
if [[ $GENERATE ]] ; then
	java -jar Hanoi.jar generate
fi



